v9y/giit

- docs/1928.isb.txt
Yea, my first pull request on the ISB! The song was missing half a line in the last stanza. I've added it. Also, a different half-line was changed in the movie version, so I added a comment. I did a bit more cleanup as well.
> Added missing half line, comment, and year; cleaned up iTrans

- docs/422.isb.txt
Another from the FITB backlog. Contributors were Uday Patel and myself. Atish Sanyal also provided the corrections/missing parts in a comment on giitaayan.
> Add missing lines and verse. Add year and credits. Correct mistakes.

- docs/1343.isb.txt
I was working on this before I got your message re: "zahar detaa hai" so I finished it up first. Will work on the latter next. This is another from the FITB archives, courtesy Malini Kanth. Still have about 20-25 of those to finish. 😬
> Add year and credits. Add sargam passage. Minor corrections.

- docs/rmim0116.isb.txt
Yikes, somehow I missed a commit that added the appropriate credits (just you and me!) to the song we just updated. Sorry about that.
> Add ISB credits

- docs/2173.isb.txt
The next one from the FITB archives. Courtesy Ramesh Subramaniam.
> Add missing stanza and credits. Correct mistakes.

- docs/1196.isb.txt
- Add prelude
- Correct lyrics errors
- Amend for style guidelines
FITB series, contributor Urzung Khan
> mere dushman tuu merii: Add prelude and correct errors

- docs/2591.isb.txt
FITB archives, courtesy Urzung Khan
> ek bewafaa se: Add missing lines, correct mistakes, add credits

- docs/552.isb.txt
> do sitaaro.n kaa zamii.n

- docs/556.isb.txt
- Add missing lines and stanza
- Add year to P-Stats
- Correct spelling mistakes
- Format
> 556: dost dost naa rahaa

- docs/1182.isb.txt
FITB archives, courtesy Urzung Khan
> 1182: meraa qaraar le jaa

- docs/1490.isb.txt
- Add Shamshad version
- Add name of stars
- Clean up style and spelling
> 1490: qusuur aap kaa, huzuur aap kaa

- docs/639.isb.txt
'sup yo. This song is actually several places down in the FITB backlog but I decided I like it too much to make it wait its turn. Missing prelude, lots of mistakes ("tuufaa.N hai zindagii kaa ab aaKharii sahaaraa"), and (gasp!) no Madhubala listed in the ISB at present.
> 639: guzaraa huaa zamaanaa

- docs/44.isb.txt
Another one from the FITB archives, courtesy Urzung Khan (he of the long memory).
> 44: aahe.n na bharii.n

- docs/749.isb.txt
Another FITB from Urzung Khan.
> 749: iinaa miinaa Diikaa

- docs/2203.isb.txt
Relatively minor update. I've known for years that the phrase is "kanchan kaayaa" and not "cha.nchal kaayaa". I have no idea how/why I missed this mistake in the song when I sent you the extra stanza via email some weeks ago. Sorry about that. While I was at it, I put a hyphen in "aa.Nch-sii" as indicated by your spelling guidelines.
> 2203: sakhii rii meraa man ulajhe

- docs/2500.isb.txt
Another one from the FITB archives, courtesy Balaji Murthy.
> 2500: zaraa-sii baat pyaar kii

- docs/1208.isb.txt
- Divide into parts
- Make lots of corrections to the lyrics
> 1208: mere mahabuub qayaamat hogii

- docs/788.isb.txt
FITB update from Ramesh Subramaniam. What a lovely song!
> 788: jaag dil-e-diiwaanaa

- docs/404.isb.txt
> 404: chhupanevaale saamane aa

- docs/1715.isb.txt
- Add year to pStats
- Bring style into conformity with guidelines
> 1715: terii pyaarii-pyaarii suurat ko

- docs/1445.isb.txt
Another beauty from the FITB archives. I don't know why Ashok (the original ISB contributor) has "morii" when the word is "merii". Also, the song is missing the third verse. This isn't actually part 2, it is just a straight-up continuation of the song: the gals go to fetch water but the well is dry, and they change their tune.
> 1445: piital kii merii gaagarii

- docs/2944.isb.txt
- Add comment
- Corrections in lyrics
> 2944: ruuTh_ke tum to chal di_e

- docs/2113.isb.txt
- Correct lyrics
- Conform to style
> 2113: juu.De me.n gajaraa mat baa.Ndho

- docs/434.isb.txt
> 434: dekh lo aaj hamako jii bharake

- docs/842.isb.txt
Years ago, when Neha sent me the FITB for "chhupanevaale saamane aa", she claimed in the cover email that I also had this one pending from her. I have no record of any submission from her for this song, but she's pretty formidable and I'm frightened of her, so I decided to be a good boy, listen to the song, and copy down the lyrics myself. So here goes. I'm pretty sure I have some of the lines wrong (e.g., "prem kii ba.nsii jahaa.N bajaataa aae shaam saveraa": it's gotta be either "shyaam" as the ba.nsiivaalaa, or "bajaate" if it's shaam-saveraa) and the idiom switches happily between Sanskrit, Hindi, and Urdu, so 'twas a challenge. Happy editing!
> 842: jahaa.N Daal-Daal par sone kii chi.Diyaa.N karatii hai.n baseraa

- docs/3339.isb.txt
> 3339: hamasafar saath apanaa chho.D chale

- docs/10316.isb.txt
The song's a mess. Here's the cleaned-up version. Rawat, bless his heart.
> 10316: ##My name is Anthony Gonsalvez##

- docs/1864.isb.txt
> 1864: vo subah kabhii to aaegii

- docs/1634.isb.txt
- Add first stanza
- Make style changes
> 1634: simaTii-sii sharamaaii-sii

- docs/15595.isb.txt
- Correct lyrics
- Modify style
> 15595: yuu.N sajaa chaa.Nd ki jhalakaa

- docs/3404.isb.txt
From the comments section on giitaayan. The commentator is K Vijay Kumar, no less.
> 3404: madabharii ye havaae.N

- docs/15212.isb.txt
Added a couple of missing words that were just ??? in the ISB. Plus a bunch of corrections.
> 15212: terii jhiil-sii gaharii aa.Nkho.n me.n

- docs/509.isb.txt
- docs/510.isb.txt
- Add missing stanza to each version
- Add year
- Correct movie title
- Edit for style
> 509–510: dil kii tamannaa thii mastii me.n

- docs/968.isb.txt
- Add missing line
- Edit for style
> 968: qasame.n ham apanii jaan kii

- docs/2964.isb.txt
- Add missing line
- Correct wrong lyrics
- Edit for style
> 2964: teraa dil kahaa.N hai

- docs/70.isb.txt
Added third verse. Song was on the FITB wishlist for a long time.
> 70: aaj se pahale, aaj se zyaadaa

- docs/2849.isb.txt
Corrections based entirely on Nimish P's comments on giitaayan. I don't even know what "ibridaa" means 🙃
> 2849: ham haal-e-dil sunaae.Nge

- docs/276.isb.txt
- Add tandem version
- Correct for style
> 276: barakhaa raanii / barakhaa bairan

- docs/333.isb.txt
Personally I find the song dullsville, but it's hugely popular, and I did remember that the Lata version had one substantially different stanza, so.....
> 333: cha.ndan-saa badan

- docs/400.isb.txt
From the FITB wishlist. Honestly, one version of the song is boring enough. Did we need a second?
> 400: chhoTii-sii ye duniyaa

- docs/2316.isb.txt
The ISB has only the very last part of this (literally) epic song. Please check carefully for typos and omissions; this was rather more challenging than usual.
> 2316: o aShaa.Dh ke pahale baadal ... duur dekh alakaapurii

- docs/2332.isb.txt
> 2332: hai tere saath merii vafaa

- docs/2608.isb.txt
- Correct film name in pStats
- Add other pStats
- Correct spelling and style
> 2608: jiivan jyot jale

- docs/908.isb.txt
Apparently K Vijay Kumar posted this on RMIM in 2010 with FITB in the subject line, but I had long left the newsgroup by then.
> 908: jurm-e-ulfat pe

- docs/1120.isb.txt
- Correct pStats
- Format and style
> 1120: mai.nne rakhaa hai muhabbat

- docs/1230.isb.txt
- Add missing stanzas
- Correct spelling and style in lyrics and pStats
> 1230: merii nii.ndo.n me.n tum

- docs/649.isb.txt
Add missing verse, general cleanup.
> 649: haal-chaal Thiik-Thaak hai

- docs/2336.isb.txt
- Add missing lines
- Correct errors
> 2336: ham tere pyaar me.n saaraa aalam

- docs/1268.isb.txt
- Correct \stitle
- Add third stanza
- Minor corrections throughout
- Format and style
> 1268: mujhako apane gale lagaa lo

- docs/145.isb.txt
- Make minor edits throughout
- Correct pStats
> 145: achchhaa unhe.n dekhaa hai, biimaar huii aa.Nkhe.n

- docs/679.isb.txt
- Correct lyrics throughout
- Correct singer information
> [Lyrics Correction] 679: ham i.ntazaar kare.nge

- docs/1307.isb.txt
- Add Lata version
- Correct spelling and style throughout
> 1307: na_ii ma.nzil na_ii raahe.n

- docs/1321.isb.txt
This song was an FITB candidate, but on checking today I found that at some point the third verse had made it into the ISB. The song needed a lot of cleanup though including spelling errors in the stitle and lyrics/spelling errors throughout. The MD's name also is spelled in a non-standard way in the pStats.
> 1321: nain hamaare saa.Njh sakaare

- docs/1337.isb.txt
- Revise comment
- Clean up spelling and style
> 1337: nazar aatii nahii.n ma.nzil

- docs/1418.isb.txt
- Format and style
- Divide into parts
> 1418: paradesio.n se na a.Nkhiyaa.N milaanaa

- docs/2930.isb.txt
> 2930: pavan diivaanii

- docs/1448.isb.txt
- Add editorial credit
- Make corrections and cleanup
> 1448: piyaa baaj pyaalaa piyaa jaae naa

- docs/1468.isb.txt
Added Part 2. Not sure why I bothered.
> 1468: puuchho na yaar kyaa huaa

- docs/2454.isb.txt
Apparently I strategically left out a couple of lines when I contributed this song to the ISB back in the mists of time. It's actually surprisingly easy to get correct/full lyrics these days, thanks to YouTube, so here's the fix.
> 2454: sai.nyaa.N binaa ghar suunaa

- docs/251.isb.txt
The ISB song is missing the prelude.
> 251: badalii-badalii duniyaa hai merii

- docs/2710.isb.txt
- Add Lata version
- Add year to pStats
- General cleanup
> 2710: taqadiir kaa fasaanaa

- docs/1720.isb.txt
- Add missing bols
- Modify \stitle
- General cleanup
> 1720: Thaa.De rahiyo, o baa.Nke yaar re

- docs/1768.isb.txt
- Add Lata version
- Modify pStats
- Minor corrections
> 1768: tum kamasin ho / mai.n kamasin huu.N

- docs/1857.isb.txt
> 1857: vo hasiin dard de do

- docs/2487.isb.txt
> 2487: vo parii kahaa.N se laauu.N

- docs/1948.isb.txt
- Add missing lines
- Make minor corrections throughout
> 1948: ye samaa.N, samaa.N hai ye pyaar kaa

- docs/3485.isb.txt
- Add Part 2
- Minor format mods
> 3485: tuu hii saagar hai tuu hii kinaaraa

- docs/427.isb.txt
- Divide into parts
- Correct pStats
- Correct lyrics errors
- Clean up style
> 427: darshan do ghanashyaam naath

- docs/321.isb.txt
Correct mistake in last verse. "bas me.n" is wrong, it should be "dafn"
> 321: bujhaa die hai.n

- docs/10302.isb.txt
Irresistible invitation to a one-night stand. I should try it the next time I see someone I fancy. On the other hand, I lack the seductiveness of both Asha and Minoo Mumtaz, so perhaps that's not such a good idea.
> 10302: tho.Dii der ke lie mere ho jaao

- docs/1207.isb.txt
- Correct lyrics
- Clean up style and format
> 1207: mere mahabuub na jaa

- docs/857.isb.txt
Added series info and did some cleanup for style. Also added the Lata solo version to the pStats.
> 857: jhilamil sitaaro.n kaa aa.Ngan hogaa

- docs/21028.isb.txt
Mainly correcting pStats. Like, it's definitely Suman and not Lata, yo. Lata was well past her prime by the mid 1970s, and Suman sounds amazingly sweet. Rafi is past his prime too, alas. Also, no Dharmendra in this movie, though I had a fun time imagining him singing this song to Jeetendra. Song is picturized on Prem Kishen (whoever he is) and Bindiya Goswami. Some minor corrections to the lyrics as well.
> 21028: terii palako.n me.n kaajal

- docs/10213.isb.txt
- docs/160.isb.txt
- docs/187.isb.txt
- docs/1964.isb.txt
- docs/2019.isb.txt
- docs/2149.isb.txt
- docs/3371.isb.txt
- docs/447.isb.txt
For 2149.isb, I made a couple of changes to make it more complete.
> Updated 2149.isb
